### ISSUE TITLE
[META] Documentation Updates for ML

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/ml-commons#1254]
**Updates to ML Documentation**
After taking a spin through some of the ML Documentation its come to my attention that it's not very conducive to newcomers in the space. There are several places where references to other documentation are needed but dont exist. Updating this will help us drive adoption especially where people are less familiar with ML type workflows. 

Below are several issues where I've proposed changes and updates to the documentation to ensure people are able to find the information they need. I'd love if you all could take a look over them and propose any updates or even contribute changes. 

- [x] https://github.com/opensearch-project/documentation-website/issues/4870
- [x] https://github.com/opensearch-project/documentation-website/issues/4869
- [x] https://github.com/opensearch-project/documentation-website/issues/4868
- [x] https://github.com/opensearch-project/documentation-website/issues/4867
- [x] https://github.com/opensearch-project/documentation-website/issues/4866

**Comment by ylwu-amzn** [comment]
Check if any chance for other plugin like KNN to enhance their doc

**Comment by SaxenaAnushka102** [comment]
Hello @dtaivpp! I'd like to work on this. Can you please tell a bit more about how can I contribute?
Thanks!
