### ISSUE TITLE
[META] ML Inference Processor Enhancements 

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/ml-commons#2839]
**Is your feature request related to a problem?**

**Search response processor:** 

- [x] support one to one inference in ml inference search response processor
- [x] support list in substring during prediction API, so it can support GenAI/RAG use case in ml inference search response with prompt defined in connector level 
- [x] support custom prompt in model config, currently it will cause escape problem, due to model Input change in this issue: https://github.com/opensearch-project/ml-commons/issues/2822 

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by mingshl** [comment]
@opensearch-project/admin -- Can you please move this to our roadmap https://github.com/orgs/opensearch-project/projects/1 under 2.17?

**Comment by mingshl** [comment]
support one to one inference in ml inference search response processor in #2801 

support list in substring during prediction API, so it can support GenAI/RAG use case in ml inference search response with prompt defined in connector level in https://github.com/opensearch-project/ml-commons/pull/2871

adding a to_string() method in httpConnector to support custom prompt in https://github.com/opensearch-project/ml-commons/pull/2871
