### ISSUE TITLE
[META] ML Inference Processor Flexibility Enhancements II

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/ml-commons#2878]
**Is your feature request related to a problem?**

- [x] Currently, search response processor can add prediction results to new fields to extensions. Try to enable option to save the model prediction to the extension part in the search response. 
- [x] For rerank use cases, we need to pass on the query_text to the model input dataset along with the documents in the search response. Try to enable reading value from query body in model config.
- [x] For rerank use cases, we also need a rescore processor that can rank the search hit and update the new scores. 

**All META Issues for ML Inference Processor:**
https://github.com/opensearch-project/ml-commons/issues/2839

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by mingshl** [comment]
closing this issue as features are implemented in 2.18
