### ISSUE TITLE
[META] ML Inference Processor Enhancements III

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/ml-commons#3054]
**Is your feature request related to a problem?**

- [ ] template query 
- [ ] ml inference search request extension
- [ ] load image from url  function in Connector (PIL.image) -- supporting image search and CLIP
- [ ] save memory --- supporting conversational search
- [ ] hide/remove field search response processor

**All META Issues for ML Inference Processor:**
https://github.com/opensearch-project/ml-commons/issues/2839
https://github.com/opensearch-project/ml-commons/issues/2878

**What alternatives have you considered?**

**Do you have any additional context?**
#2173

**Comment by brianf-aws** [comment]
Linking https://github.com/opensearch-project/ml-commons/issues/3152 as it relates to image support

**Comment by brianf-aws** [comment]
Hi, for the  `load image from url function in Connector (PIL.image) -- supporting image search and CLIP` task we have to put on pause as our internal security team has stated explicitly that they don't want us to implement this (has to many edge cases).

Currently ML Commons supports for base64 strings that are used to invoke multi-modal models. Full end to end workflows were done to see that this is possible, without downloading from URL

**Comment by mingshl** [comment]
updating: 

save memory --- supporting conversational search --targeting 3.1

hide/remove field search response processor --targeting 3.1
